functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  non-functional:
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Регистрация пользователя
  - Авторизация пользователя
  - Пользователь должен иметь возможность редактировать содержимое корзины
  - Пользователь должен иметь возможность редактировать количество единиц каждого товара в корзине
  - Должна быть предусмотрена возможность оплаты товара из корзины
  - Должна быть предусмотрена возможность оплаты товара напрямую из каталога
  - Должно быть предусмотрено предоставление информации об успешной оплате товара
  - Должно быть предусмотрено предоставление информации о статусе заказа
  - Карточка товара должен содержать информацию о цене, цвете, размере   
  - Сайт должен работать на мобильных и десктопных устройствах
  - Должен быть предусмотрен выбор основного языка просмотра
  - При выборе языка текстовые подсказки внутри фильтров должны изменить язык в соответствии с выбранным основным языком сайта
  - Должна быть реализована возможность перехода между страницами каталога
